### ISSUE TITLE
Add ARM wheel for M1 Mac processors

### ISSUE THREAD

**Issue by BestQuark** [quantumgizmos/ldpc#11]
Hello 😄, 
Currently ldpc cannot be installed with `pip install ldpc` in M1 Macs because it does not have a ARM wheel in PyPi. It would be nice to add this wheel.

**Comment by quantumgizmos** [comment]
Hi
The latest version ```ldpc 0.1.45``` has ARM64 wheels. Could you test it on your M1 Mac and let me know whether it works?
Thanks
Joschka

**Comment by BestQuark** [comment]
Works great! Thanks Joschka
