### ISSUE TITLE
BeliefFind gets stuck in `peeling` mode.

### ISSUE THREAD

**Issue by timohillmann** [quantumgizmos/ldpc#30]
For some syndromes, the BeliefFind decoder seems to get stuck in `peeling` mode and will not terminate. This error does occur in `inversion` mode. In particular, I find that for the example below the `i = 8` that is the syndrome `s = [0 0 1 0 0 0]` is problematic.

To reproduce run

```python 

import numpy as np
from ldpc.belief_find_decoder import BeliefFindDecoder
from scipy.sparse import load_npz


def load_surface_code(d: int):
    hx = load_npz(
        f"/Users/timo/Documents/GitHub/ldpc/python_test/pcms/hx_surface_{d:d}.npz"
    )
    lx = load_npz(
        f"/Users/timo/Documents/GitHub/ldpc/python_test/pcms/lx_surface_{d:d}.npz"
    )

    return hx, lx


if __name__ == "__main__":
    d = 3
    hx, lx = load_surface_code(d)
    decoder = BeliefFindDecoder(
        hx,
        error_rate=0.05,
        max_iter=4,
        bp_method="ms",
        ms_scaling_factor=0.625,
        schedule="parallel",
        uf_method="peeling",
    )

    m, n = hx.shape

    # iterate through all possible syndrome strings
    for i in range(2**m):
        s = np.array([int(x) for x in list(f"{i:0{m}b}")])
        print(i, s)
        corr = decoder.decode(s)
```

**Comment by quantumgizmos** [comment]
Can you upload the surface code PCMs you are using?

**Comment by timohillmann** [comment]
It's the on-branch `l4_dev` pcms stored at `python_test/pcms/hx_surface_3.npz`

**Comment by quantumgizmos** [comment]
All of d=3 surface code syndromes work for me.

**Comment by quantumgizmos** [comment]
I have found that `error = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])` for d=5 causes the decoder to crash though in Peeling mode

**Comment by quantumgizmos** [comment]
It works in all cases for me if you set `uf_method = "peeling"` and `bits_per_step = 1`.

There is something going wrong with `error = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])` on the d=5 surface code when the `bits_per_step > 5`. Will investigate.

**Comment by timohillmann** [comment]
I get stuck even with `bits_per_step = 1`. For the `d=3` surface code, the following error causes a problem `[0 0 0 0 0 0 0 0 1 0 0 1 0]`
Note that I am running `python/3.11.7` on intel-mac.

**Comment by quantumgizmos** [comment]
Can you try in a fresh python virtual environment?

**Comment by timohillmann** [comment]
With a fresh environment, d = 3, 4, 5 work with `bit_per_step = 1`. Thanks
