### ISSUE TITLE
[AWGN Channel]

### ISSUE THREAD

**Issue by kaposnick** [quantumgizmos/ldpc#34]
Hi! I am particularly interested in BP decoding for BI-AWGN channels. Is it in the roadmap to be implemented?

**Comment by quantumgizmos** [comment]
Hi. It would be good to implement this functionality at some point. I think it would require only a small change to the existing syndrome-based implementation. We're currently working on LDPCv2. The BP decoder code can be found in this branch https://github.com/quantumgizmos/ldpc/blob/ldpc_v2/src_cpp/bp.hpp

If you can see a way of modifying this for AWGN, please put in a PR

**Comment by kaposnick** [comment]
Thanks for the pointer! I will come back on it.
