### ISSUE TITLE
AttributeError: module 'warnings' has no attribute 'warning' in ldpc.code_util.compute_exact_code_distance(H)

### ISSUE THREAD

**Issue by anupamsworld** [quantumgizmos/ldpc#47]
Calling ldpc.code_util.compute_exact_code_distance(H) gives warning if H is large but for using the "warnings.warning" API the following error is raised.
warnings.warning("This function has exponential complexity. Not recommend for large pcms. Use the\
    ^^^^^^^^^^^^^^^^
AttributeError: module 'warnings' has no attribute 'warning'
When I searched inside "warnings" module, I did not find any function called "warning" but "warn".

**Comment by quantumgizmos** [comment]
Thanks for reporting this. This should be fixed now.
