### ISSUE TITLE
Stubfile formatting

### ISSUE THREAD

**Issue by quantumgizmos** [quantumgizmos/ldpc#48]
In VsCode, typehints for classes are incorrectly formatted. This is likely a problem with the stubfiles that are automatically generated in `setup.py`. See attached screenshot for an example:

<img width="791" alt="typehint_example" src="https://github.com/user-attachments/assets/f74f46e2-4f3a-4899-9c35-4fdbddcb8af7">

**Comment by perlinm** [comment]
My mistake!  I think this should be fixed by #50
