### ISSUE TITLE
Unit test failing

### ISSUE THREAD

**Issue by quantumgizmos** [quantumgizmos/ldpc#6]
See `dev` branch `test_ring_of_circulants_f2.py`.

The following test is failing:

```
d = RingOfCirculantsF2([1])
f = RingOfCirculantsF2([1,1])
assert (f+d) == [1]
```

**Comment by peter-janderks** [comment]
Defining an element in ring of circulantslike this:

f = RingOfCirculantsF2([1,1])

seems a bit strange to me for the field F2. What do you think? I could change the __init__ function, but this would slow things down.

I still like using the set operation for addition, because &lambda;(1,2) + &lambda;(1) = &lambda;(2) seems more intuitive to me (and more memory efficient)

**Comment by quantumgizmos** [comment]
My concern is that it doesn't match the behavior of the matrix representation of these ring elements. This is why I initially just defined addition as a concatenation of the lists. Is concatenation significantly slower than the set operation?

An alternative would be to implement some sort of simplification routine that counts whether there are an odd or even number of repetitions of the same coefficient and deletes accordingly.

**Comment by quantumgizmos** [comment]
I would also add that it is odd to define an element like

```
RingOfCirculantsF2([1,1])
```
However, it's conceivable that such an object might arise as part of some numpy subroutine we might want to apply. Eg., numpy.kron may end up in situations where such a ring element arises.

**Comment by peter-janderks** [comment]
Ok, we could change again to appending lists. Can you make the changes?

numpy kron uses the multiplication defined here so that satuation does not occure. (I thought about this a bit, there are tests in the QEC package)

**Comment by peter-janderks** [comment]
the speed difference was not in the difference between appending lists and the set operation but with multiplying,
instead of multiplying [1, 1, 1, 1, 1] x [2] it should multiply [1] x [2].
